### PR TITLE
Fix regression tests following release of r2dii.data v0.1.7

### PR DESCRIPTION
**Pull request by maurolepore**
This is to confirm what i see locally -- that following the release of r2dii.data v0.1.7, multiple regression tests fail in r2dii.match. 

Results of `git bisect`:

```bash
rstudio@4aefb68a75ce:~/git/r2dii.data$ git bisect good
7199b298fd49c8646238d99ec179d23b5915353c is the first bad commit
commit 7199b298fd49c8646238d99ec179d23b5915353c
Author: Jackson Hoffart <jackson.hoffart@gmail.com>
Date:   Mon Feb 8 16:17:52 2021 +0100

    Add hdv technology identifications to `green_or_brown` (#198)
    
    
    Co-authored-by: Mauro Lepore <maurolepore@gmail.com>

 data-raw/ald_demo.csv                   | 34838 +++++++++++++++---------------
 data-raw/green_or_brown.csv             |     4 +
 data-raw/loanbook_demo.csv              |   643 +-
 data/ald_demo.rda                       |   Bin 224802 -> 198276 bytes
 data/green_or_brown.rda                 |   Bin 333 -> 366 bytes
 data/loanbook_demo.rda                  |   Bin 11602 -> 11580 bytes
 man/ald_demo.Rd                         |     2 +-
 man/green_or_brown.Rd                   |     2 +-
 man/loanbook_demo.Rd                    |     2 +-
 tests/testthat/_snaps/ald_demo.md       |    28 +-
 tests/testthat/_snaps/green_or_brown.md |     8 +-
 tests/testthat/_snaps/loanbook_demo.md  |    40 +-
 tests/testthat/helper-round_dbl.R       |     5 +
 tests/testthat/test-ald_demo.R          |     2 +-
 14 files changed, 17842 insertions(+), 17732 deletions(-)
rstudio@4aefb68a75ce:~/git/r2dii.data$ 
```

### CODE REVIEW

**Comment by maurolepore** [comment]
My regression tests shows the line 321 is now and contains the string "Zotye Auto HDV".



Searching for that string I confirm it was first introduced at the commit that `git bisect` pointed as the first bad commit.

```bash
rstudio@4aefb68a75ce:~/git/r2dii.data$ git log -S "Zotye Auto HDV"
commit 7199b298fd49c8646238d99ec179d23b5915353c (refs/bisect/bad)
Author: Jackson Hoffart <jackson.hoffart@gmail.com>
Date:   Mon Feb 8 16:17:52 2021 +0100

    Add hdv technology identifications to `green_or_brown` (#198)
    
    
    Co-authored-by: Mauro Lepore <maurolepore@gmail.com>
rstudio@4aefb68a75ce:~/git/r2dii.data$ 
```

This seems like an intentional change so I'll go ahead and run `snapshot_accept('add_sector_and_borderline')`.

**Comment by maurolepore** [comment]
Consistently, the failing test of `match_name()` also suggests the difference against the snapshot is due to two lines, 409 and 410,  that also contain the string "Zotye Auto HDV".




Again, this looks intentional so I run `snapshot_accept('match_name')`.

**Review by jdhoffa — APPROVED** [review]
Yup this is totally fine. Also speaks to the bigger issue of regression tests.

**Comment by jdhoffa** [comment]
To keep track of the broader issue that we spoke about, @maurolepore , I added a card to the project "r2dii" (I know this is sorta an unused project board, but I couldn't think of a better place for r2dii-wide issues): https://github.com/orgs/2DegreesInvesting/projects/8#card-55260752

**Pull request merged**
