### PR TITLE
update snapshot values due to change in how tibbles are printed

### PR DESCRIPTION
**Pull request by jdhoffa**
Changes in how tibbles print have caused the snapshot output of certain tests to fail. I have updated the regression tests here.

Relates to #407

### CODE REVIEW

**Comment by cjyetman** [comment]
just out of curiosity, why are you testing a snapshot of the tibble console output instead of testing the actual data in it?

**Comment by AlexAxthelm** [comment]
Is this documentation for the test?

**Review by AlexAxthelm — APPROVED** [review]

**Comment by jdhoffa** [comment]
> just out of curiosity, why are you testing a snapshot of the tibble console output instead of testing the actual data in it?

Honestly I have no idea, `r2dii.match` was maintained mostly by Mauro, I just took over maintenance when we switched to RMI. I'll git blame and see if there's a reason

**Comment by jdhoffa** [comment]
> > just out of curiosity, why are you testing a snapshot of the tibble console output instead of testing the actual data in it?
> 
> Honestly I have no idea, `r2dii.match` was maintained mostly by Mauro, I just took over maintenance when we switched to RMI. I'll git blame and see if there's a reason

Ok so this is just the default behaviour of `expect_snapshot` in `testthat 3e`: 
https://testthat.r-lib.org/reference/expect_snapshot.html
https://testthat.r-lib.org/articles/snapshotting.html

**Comment by jdhoffa** [comment]
So I don't think the value of the data actually matters here. The `expect_snapshot` call occurs in the test `warns overwrite`, which is just expecting a certain warning. I think the snapshot might just be used so a human can visually expect if the warning is correct? I'm not sure. 

A PR will follow to specify warning `class` instead and remove this snapshot.

**Comment by jdhoffa** [comment]
@AlexAxthelm if you can think of another reason why `expect_snapshot` would be useful in this circumstance please let me know, otherwise I'm in favour of removing it.

**Comment by AlexAxthelm** [comment]
I'm generally in favor of replacing snapshots with less brittle tests.

**Pull request merged**
