### PR TITLE
By_sector flag now successfully applies to  final joining of lbk and ald

### PR DESCRIPTION
**Pull request by jdhoffa**
Solves #111

### CODE REVIEW

**Comment by jdhoffa** [comment]
f389177 I was going to ask you about this! 

It seemed so dumb to pass such a small `else` statement, but I wasn't sure of the most concise way to write it. Also can't believe i forgot the `.data` haha

**Comment by maurolepore** [comment]
> It seemed so dumb to pass such a small else statement

Some people prefer to use else, even if it can be avoided because it can make the code more readable. As long as that is the purpose, I think it's okay.

What I like of just using if is that if forces me to think about the most succinct way to do the job. And if I find that way is poorly readable, then I can add a superfluous `else` just for clarity.

**Comment by maurolepore** [comment]
Checks pass on Travis CI except with R-devel. The problem seems to be external and ephemeral (relates to the pillar and readr packages) so I'll go ahead and merge.

**Comment by maurolepore** [comment]
Just for fun and to honour [Code smells and feels, by Jenny Bryan](https://github.com/jennybc/code-smells-and-feels/blob/master/2018-07_user-brisbane-bryan.pdf):

**Pull request merged**
