### PR TITLE
Don't expect a specific state we want to change frequently

### PR DESCRIPTION
**Pull request by maurolepore**
Locally I see a regression test fail. I wonder if I see the same on CI.

### CODE REVIEW

**Comment by maurolepore** [comment]
@jdhoffa, can you help me figure out what's going on here?

I see an error locally and on CI. This is surprising because the last commit (several days ago) seem to have [passed all checks](https://github.com/2DegreesInvesting/r2dii.match/commits/master), and this PR adds nothing but an empty commit.

**Comment by jdhoffa** [comment]
I see tests fail too. I think this is somehow linked to us changing required datasets in `r2dii.data`, and it affecting the output of `r2dii.match`. This has been a problem in the past as well. 

I think our best option would be to somehow remove the dependency on `r2dii.data` entirely from the tests of `r2dii.match`. The only issue is that the sector classifications are pulled in directly from there (internally in `match_name`)

**Comment by jdhoffa** [comment]
I think this actually could relate to #314 
If we allow the sector bridge to be passed in as an argument, we can write a helper function in `r2dii.match` to ensure that we have a stable testing environment, regardless of what we do to `r2dii.data`

**Comment by jdhoffa** [comment]
Ya, as expected, the error comes from testing that the sector classification code system is known. 
See the test failure here: 
``` r
  ""
  "> match_name(all_bad_code, fake_ald())"
  "Error: Some `sector_classification_direct_loantaker` must be known, i.e. one of:"
- "A, 1, 11, 111, 112, 113, 114, 115, 116, 119, 12, 121, 122, 123, 124, 125, 126..."
+ "10101010, 10101020, 10102010, 10102020, 10102030, 10102040, 10102050, 1510101..."
  ""
  "> match_name(all_bad_system, fake_ald())"
  "Error: Some `sector_classification_system` must be known, i.e. one of:"
- "ISIC, NACE, NAICS and SIC"
+ "GICS, ISIC, NACE, NAICS and SIC"
```

What has happened is that we have added the new `GICS` sector to the list of possible sector classification systems, which now outputs a new system and code. 

My vote would be to remove this explicit check for the "output" of this warning/ error as it is likely to change frequently. Is there a reason that it is necessary? Is it sufficient just to check that there is an error/ warning with an appropriate class?

**Comment by jdhoffa** [comment]
I have removed the explicit check for the expected warning/ error message if unknown sector classifications are provided. 

I guess it is not the most satisfactory solution to just delete the failing test, however I think it is sufficient given what I wrote above, in particular that we check that the error and warning classes are correct. 

If you disagree, feel free to revert the commit and we can think of another solution <3

**Pull request merged**
