### PR TITLE
Polish docs

### PR DESCRIPTION
**Pull request by maurolepore**

### CODE REVIEW

**Comment by maurolepore** [comment]
@jdhoffa, here I try to make out docs easier to reuse and maintain. 

I hope the commit and message are clear. 

Something maybe unclear:

* In the vignettes, I removed the numbering to make it easier to maintain. Numbering makes if hard to move move sections around or to downgrade a section to a subsection.

**Comment by jdhoffa** [comment]
also regarding the code running in README, that was a mistake on my part. 
Didn't mean to switch `{r}` to `r` (if you know what I mean)

**Comment by maurolepore** [comment]
RE:  "out of the prioritize() description"

`prioritize()` contains the same "validate" instructions that give in Get started. We inject that here:
https://github.com/2DegreesInvesting/r2dii.match/blob/358dc67b9e5a70ce617c6c5cc2971a7dc952c204/R/prioritize.R#L19

Unfortunately the website still doesn't reflect that because [the site failed to build](https://github.com/2DegreesInvesting/r2dii.match/runs/457367587?check_suite_focus=true) but that should be an easy fix that I'll do next.

**Comment by jdhoffa** [comment]
Ah ok understood, I see that now! I had only looked at the code, and thought it was including a hyperlink to a documentation page or something similar

**Comment by maurolepore** [comment]
The job is done. See:
* [source](https://github.com/2DegreesInvesting/r2dii.match/blob/master/vignettes/_validate-matches.md).
* usage in [`?prioritize()`](https://2degreesinvesting.github.io/r2dii.match/reference/prioritize.html#details).
* usage in [Get started](https://2degreesinvesting.github.io/r2dii.match/articles/r2dii.match.html#validate-matches).

**Pull request merged**
